import unittest

import unittest
import db_funcs_for_subject_db_unittests
import find_class_location_unittests
import find_lessons_at_date_unittests
import find_time_and_location_unittests
import request_handler_unittests
import site_parser_undergraduate_unittests

calcTestSuite = unittest.TestSuite()
calcTestSuite.addTest(unittest.makeSuite(db_funcs_for_subject_db_unittests.Test_db_funcs_for_subjects_db))
calcTestSuite.addTest(unittest.makeSuite(find_class_location_unittests.Test_find_class_location_find_class_location))
calcTestSuite.addTest(unittest.makeSuite(find_lessons_at_date_unittests.Test_find_lessons_at_date_return_lessons_at_date))
calcTestSuite.addTest(unittest.makeSuite(find_time_and_location_unittests.Test_return_location_of_class))
calcTestSuite.addTest(unittest.makeSuite(find_time_and_location_unittests.Test_find_time_and_location_return_text_about_time_before_lesson_with_location))
calcTestSuite.addTest(unittest.makeSuite(request_handler_unittests.Test_request_handler))
calcTestSuite.addTest(unittest.makeSuite(site_parser_undergraduate_unittests.Test_site_parser_undergraduate))

runner = unittest.TextTestRunner(verbosity=1)

if __name__ == '__main__':
    runner.run(calcTestSuite)
